### ISSUE TITLE
Integrar com analises estáticas 

### ISSUE THREAD

**Issue by pauloborba** [spgroup/miningframework#11]

**Comment by pauloborba** [comment]
vide o repositório compartilhado por rodrigo bonifácio

**Comment by pauloborba** [comment]
@rafaelmotaalves esse é o próximo passo depois de arrendodar a coleta do dataset

**Comment by pauloborba** [comment]
@rafaelmotaalves acho que já podemos começar aqui, certo?

**Comment by rafaelmotaalves** [comment]
@pauloborba sim

**Comment by pauloborba** [comment]
passos

1. entender o codigo de Rodrigo
2. testar o codigo dele
3. alterar implementacao de alguma das interfaces para chamar o codigo dele a partir do framework e popular a planilha com os resultados

**Comment by rafaelmotaalves** [comment]
Comecei a testar manualmente o framework com algumas entradas. Mas só vou conseguir integrar quando concluir a issue #42
