### ISSUE TITLE
Some of the static-analysis implementation dependencies are not properly documented

### ISSUE THREAD

**Issue by rafaelmotaalves** [spgroup/miningframework#114]
We should document the following dependencies:
* Python 3 to execute the python scripts
* The python scripts dependencies (the requests libs), maybe we should use a requirements.txt file at the scripts folders to add those dependencies so that the user can execute  `pip3 install -r requirements.txt` to execute all dependencies
* The [diff](https://man7.org/linux/man-pages/man1/diff.1.html) command-line tool (native to Linux)

**Comment by barbosamaatheus** [comment]
Guys, I found this here: http://www.cygwin.com/

It may be possible to use Diff on windows when installing this tool. What do you think?

**Comment by rafaelmotaalves** [comment]
Looks like a good alternative, can you test it? @barbosamaatheus

**Comment by pauloborba** [comment]
@barbosamaatheus better not to invest time on that. just list the OS and associated constraints. cygwin works, but is basically a shell running inside windows.
