### ISSUE TITLE
Refatorar o código

### ISSUE THREAD

**Issue by pauloborba** [spgroup/miningframework#13]

**Comment by rafaelmotaalves** [comment]
* Mover Main para começo da classe
* Parse imprimindo Help não está claro
 * Deixar flag do create output files mais clara
* Substituir ArrayList no start para tipo Abstrato
* Renomear collectData para collectExperimentalData
* Renomear classe DataCollector para ExperimentalDataCollector
* Trocar de classe pra interface DataCollector, StatisticsCollector e CommitFilter
* Adicionar links no StatisticsCollector
* Adicionar data na mensagem de commit
* Renomear FileManager.createDataFiles para createExperimentalDataFiles
* Criar método argumentsSize em no ArgsParser

**Comment by jvcoutinho** [comment]
- Extrair método da condição do comando de push
- Extrair métodos do parsing do output do git log
- Refatorar o restante dos ProcessBuilders

**Comment by pauloborba** [comment]
@jvcoutinho esta issue já pode ser fechada?
