### ISSUE TITLE
Refatorar o código das classes de serviços

### ISSUE THREAD

**Issue by rafaelmotaalves** [spgroup/miningframework#20]
- [x] Melhorar contagem de conflitos e arquivos com conflito (com expressões regulares)
- [x] Verificar se o ```git show``` é uma boa solução
- [x] Tratar caso em que a mais de dois pares, no calculo de entre datas de commit (StatisticalCollector)
- [x] Extrair método de getMutuallyModified
- [x] Rename analyseModifiedMehtods e assembleResults
- [ ] Melhorar legibilidade do getModifiedMethods

**Comment by rafaelmotaalves** [comment]
@pauloborba Só checando se encontra o marcador de conflito só detectaria se o conflito for para o repositório remoto (o que quase nunca acontece), a alternativa que achei foi dar checkout para o commit head de left e dar merge com o commit head de right, e daí procurar pelos marcadores, faço assim?

**Comment by rafaelmotaalves** [comment]
@jvcoutinho

**Comment by pauloborba** [comment]
Sim Rafael

**Comment by jvcoutinho** [comment]
O git merge também dá como saída os conflitos que ocorreram, algo como
CONFLICT [...]
Dá pra contar eles.

**Comment by pauloborba** [comment]
@jvcoutinho tu revisas o PR #22 para fecharmos esta issue?
