### ISSUE TITLE
Configurar o travis

### ISSUE THREAD

**Issue by pauloborba** [spgroup/miningframework#23]

**Comment by rafaelmotaalves** [comment]
Aparentemente o padrão do travis é configurar usando ferramentas de build, no caso de groovy qual é a melhor opção: maven, ant ou gradle? @pauloborba @jvcoutinho

**Comment by pauloborba** [comment]
maven. pesquisar melhor essa resposta do junit/testes do groovy. @rafaelmotaalves

**Comment by rafaelmotaalves** [comment]
@pauloborba não achei nenhuma referência a esse problema, mas todos os testes que eu fiz com groovy, mesmo com exception não feitas pelo teste, o código retornado foi 0. Você conhece alguém que tenha configurado o travis para testar groovy que eu possa falar?

**Comment by pauloborba** [comment]
@rafaelmotaalves será que as referências abaixo ajudam? a discussão inicial da primeira confirma as suas observações. https://stackoverflow.com/questions/9316218/how-to-set-the-exit-status-in-a-groovy-script#9330130 https://stackoverflow.com/questions/32418722/travisci-is-not-failing-my-build-when-tests-fail

**Comment by rafaelmotaalves** [comment]
Não consegui configurar o JUnit pra mudar o exit code, a alternativa que eu achei foi fazer um wrapper para o assert, e usar ele nos testes.

O código dele ficaria assim:
```groovy
public void assertTrue(boolean value) {
	try {
		assert value
	} catch (AssertionError e) {
		e.printStackTrace()
		System.exit(1)
	}
}
```

Pode ser @pauloborba ?

**Comment by pauloborba** [comment]
@rafaelmotaalves isso não vai fazer com que o junit deixe de executar os demais testes assim que o primeiro falhe?

**Comment by rafaelmotaalves** [comment]
Sim @pauloborba

**Comment by pauloborba** [comment]
@rafaelmotaalves, qual então o problema com a solução de configurar o JUnit? aparenta ser mais interessante

**Comment by rafaelmotaalves** [comment]
Na verdade a configuração que tava pensando em fazer era configurar uma função para ser rodada após algum teste falhar, e essa função ia dar o exit, mas eu não consegui fazer funcionar. mas teria esse mesmo problema. @pauloborba

**Comment by pauloborba** [comment]
melhor focar na outra tarefa entao. deve ter uma solucao melhor para este problema aqui, mas eu teria que investigar mais.

**Comment by pauloborba** [comment]
tenta só pesquisar se para Java seria a mesma coisa
