### ISSUE TITLE
A ferramenta faz múltiplas operações de I/O desnecessárias

### ISSUE THREAD

**Issue by jvcoutinho** [spgroup/miningframework#29]
Sempre que o programa executa `copyFile`, ele faz uma operação de I/O (escrita no arquivo) para cada linha da saída do comando `git cat-file`, que retorna o conteúdo de um arquivo em um commit. Isso torna o processo bem lento.

https://github.com/spgroup/miningframework/blob/391a61b87b205385173f2fd0b59bdcea9adfbfd4/src/main/util/FileManager.groovy#L26-L34

Eu proponho colocar toda a saída na memória (em uma string, por exemplo), e só realizar a escrita no arquivo no fim do processo.

**Comment by jvcoutinho** [comment]
Isso possivelmente acontece em outros comandos executados pelo `ProcessRunner`.

**Comment by pauloborba** [comment]
não temos na API de Java algum método que já faça essa cópia de forma mais eficiente? e uma forma de pegar o arquivo em um commit, ao invés de dar cat nele?

**Comment by pauloborba** [comment]
@rafaelmotaalves

**Comment by rafaelmotaalves** [comment]
Vou investigar essas otimizações.

**Comment by rafaelmotaalves** [comment]
Sobre isso, eu percebi que um dos casos que são feitas muitas operações de IO, são quando são escritas a linhas da resposta. Vocês acham que seriam um boa abordagem adicionar um tipo genérico ou uma classe abstrata pra representar um estrutura de dados que poderia ser montanda durante a análise?

**Comment by rafaelmotaalves** [comment]
Um vantagem dessa abordagem, seria que deixaria mais fácil utilizar o framework através de código, podendo ser útil pra análises futuras, além de diminuir a quantidade de operações de IO, que poderiam ser reduzidas a um escrita no fim da análise.

**Comment by rafaelmotaalves** [comment]
@pauloborba @jvcoutinho

**Comment by pauloborba** [comment]
Isso não é prioridade agora.

Quando for, uma opção não seria simplesmente usar uma estrutura padrão (essencialmente um buffer string) que escreve para o arquivo em blocos de um determinado tamanho?

Essa solução não seria satisfatória para praticamente todos os usuários?

**Comment by rafaelmotaalves** [comment]
Talvez, mas não daria a possibilidade de criar estruturas de dados mais complexas, como uma árvore por exemplo, que poderia ser lida por código. Mas o problema de IO resolveria sim

**Comment by pauloborba** [comment]
melhor então, por enquanto, só atacar o problema de IO.

**Comment by rafaelmotaalves** [comment]
Quanto a esse problema da IO, pelo o que eu vi tem duas alternativas:
*  Dar checkout no commit para ler o conteúdo do arquivo
* Criar o arquivo diretamente no comando de terminal

Eu acho que nenhuma dessas alternativas é melhor do que a solução atual, o que vocês acham?
