### ISSUE TITLE
Adicionar testes de regressão

### ISSUE THREAD

**Issue by pauloborba** [spgroup/miningframework#3]

**Comment by pauloborba** [comment]
@rafaelmotaalves a prioridade aqui deve ser em testes que, principalmente, verificam se as linhas modificadas por left e right foram realmente detectadas pela ferramenta, e se a ferramenta reporta apenas linhas de fato modificadas.

**Comment by rafaelmotaalves** [comment]
@pauloborba fiz alguns repositórios de teste para verificar alguns casos manualmente, principalmente situações que left e right fazem a mesma modificação na mesma linha (modificações diferentes causariam conflitos) e algumas que testam adições, remoções e o filtro. Adiciono eles no repositório principal? Faço alguma forma de verificar os valores automáticamente?

**Comment by rafaelmotaalves** [comment]
Pela minha verificação todas essas situações estão funcionando

**Comment by pauloborba** [comment]
> @pauloborba fiz alguns repositórios de teste para verificar alguns casos manualmente, principalmente situações que left e right fazem a mesma modificação na mesma linha (modificações diferentes causariam conflitos) e algumas que testam adições, remoções e o filtro. Adiciono eles no repositório principal? Faço alguma forma de verificar os valores automáticamente?

sim @rafaelmotaalves, por favor. a ideia é que esses testes automatizados sejam adicionados ao repositório e automaticamente executados (via travis) toda vez que submetermos novas contribuições.

**Comment by rafaelmotaalves** [comment]
Pelo o que eu entendi para adicionar um submódulo, você tem que ter o remote dele, ou seja, tem que criar um repositório no github para cada repositório de testes, faço assim?

**Comment by pauloborba** [comment]
@rafaelmotaalves nesse caso, de colocar no github, nem precisaria colocar como submódulo. como esse repositório de testes é estático, acredito que a solução mais simples seria sem submódulos mesmo, e sem projeto no github. em diretórios tests/projectX, tests/projectY, etc. você simplesmente coloca os repositórios git de teste e dá commit normalmente, como esses diretórios não contivessesm projeto git. seria interessante colocar como submódulo caso a gente quisesse evoluir esses repositórios de teste de forma independente do projeto do framework.

**Comment by rafaelmotaalves** [comment]
@pauloborba o problema é que o git automáticamente ignora a pasta .git, ai não da pra fazer as análises.
Uma alternativa seria a gente criar um repositório único e colocar ele no github, com um arquivo pra cada caso de teste.

**Comment by pauloborba** [comment]
tem razão @rafaelmotaalves! melhor então a solução de criar os repositórios de teste no github mesmo, e tê-los como sub-módulos como garantia de que as dependências eventualmente não vão ser quebradas.
