### ISSUE TITLE
Algumas opções de linha de comando são relacionadas a implementações específicas dos hooks, não ao framework

### ISSUE THREAD

**Issue by pauloborba** [spgroup/miningframework#30]

**Comment by rafaelmotaalves** [comment]
@pauloborba Quais seriam essas opções? Eu devo remover elas?

**Comment by pauloborba** [comment]
olha o comentário que fiz sobre um dos comentários de @jvcoutinho no último PR

**Comment by pauloborba** [comment]
verificar se há alguma opçao que seja específica da implementacao de uma das interfaces ao inves do framework em sim.

**Comment by rafaelmotaalves** [comment]
@pauloborba pelo o que eu verifiquei todos são necessários para o framework

Em qua, 28 de ago de 2019 às 18:10, Paulo Borba <notifications@github.com>
escreveu:
