### ISSUE TITLE
Adicionar suporte a vários CommitFilters.

### ISSUE THREAD

**Issue by rafaelmotaalves** [spgroup/miningframework#39]
A ideia seria definir uma strategy para escolher quais filtros devem ser aplicados.

**Comment by pauloborba** [comment]
@rafaelmotaalves mas acredito que a gente já tenha implementado algum mecanismo para isso, não?

**Comment by rafaelmotaalves** [comment]
Atualmente, o framework recebe uma classe CommitFilter, que poderia reunir o comportamento de várias classes. Mas a ideia seria receber diretamente uma lista de CommitFilters, e o framework fica resposável por associar eles.

**Comment by pauloborba** [comment]
talvez seja melhor deixar assim mesmo, recebendo apenas uma. e assumir que a logica de combinacao de filters (atraves de ANDs, ORs, etc.) fique a cargo de quem vai definir o filtro. um filtro novo pode ser feito combinando filtros existentes.

**Comment by rafaelmotaalves** [comment]
Ok, de qualquer forma, devo separar a lógica dos filtros já implementados em outras classes?

**Comment by rafaelmotaalves** [comment]
Com cada classe responsável por um

**Comment by pauloborba** [comment]
mantém. isso pode ser feito sob demanda por quem precisar de filtros menos restritivos.
