### ISSUE TITLE
Filtrar commits que as alterações foram nas mesmas linhas

### ISSUE THREAD

**Issue by rafaelmotaalves** [spgroup/miningframework#43]
@pauloborba percebi que muitos dos commits coletados só tem alterações na mesmas linhas. Deveriamos filtrar esses? Já que a ferramenta sempre vai achar fluxos.

**Comment by pauloborba** [comment]
@rafaelmotaalves algum progresso aqui?

**Comment by rafaelmotaalves** [comment]
@pauloborba ainda não, devo priorizar isso antes de rodar os cenários?

**Comment by pauloborba** [comment]
@rafaelmotaalves rodar os cenários é mais importante

**Comment by rafaelmotaalves** [comment]
Fazer esse filtro ao montar os csvs de entrada do soot.

**Comment by pauloborba** [comment]
OK, melhor mesmo fazer isso na chamada do SOOT, ao invés de remover da lista/planilha, ou mesmo fazer isso na implementação SOOT. 

deixar na lista sinalizaria conflito quando não há, como em os dois desenvolvedores adicionam x=1, e um deles, mais abaixo, adiciona y=x. haveria fluxo e portanto conflito, assumindo que a linha de x=1 aparece na lista de mudanças dos dois desenvolvedores.
