### ISSUE TITLE
Remover o filtro de conflitos textuais e adicionar a informação de houve conflito ou não na planilha de resultados

### ISSUE THREAD

**Issue by rafaelmotaalves** [spgroup/miningframework#45]

**Comment by rafaelmotaalves** [comment]
@pauloborba como isso deve ser feito? o merge usado na análise tem que ser o resultante do merge com o s3m?

**Comment by pauloborba** [comment]
isso. ao inves de chamar git merge e verificar se ha conflito, voce vai chamar s3m e verificar se ha conflito.

**Comment by rafaelmotaalves** [comment]
mas pode usar o arquivo resultante que ta no git?

**Comment by rafaelmotaalves** [comment]
que provavelmente algum desenvolvedor resolveu o conflito

**Comment by pauloborba** [comment]
hum! pensando melhor, já que alguém corrigiu o conflito textual, talvez a gente não devesse filtrar esses casos.

se a resolução do desenvolvedor for igual ao resultado do s3m, seria um potencial candidato para conflito semântico.

se a resolução não for igual, a gente não teria certeza se seria conflito semântico mesmo ou se a possível bronca tenha sido causada pela “correção” do conflito textual.

assim, ao invés de filtrar esses casos, talvez seja melhor colocá-los no dataset, adicionando uma coluna apenas para a gente saber se houve conflito textual ou não.

**Comment by rafaelmotaalves** [comment]
Não entendi, qual seria a abordagem? Não filtrar com o s3m?

**Comment by pauloborba** [comment]
não filtrar casos que tenham conflito. mas coletar uma informacao a mais na planilha (coluna que indica se para um dado cenario/linha houve conflito no textual).

**Comment by rafaelmotaalves** [comment]
Ok, seria na mesma planilha que são coletadas as linhas certo?

**Comment by pauloborba** [comment]
Isso
