### ISSUE TITLE
Adicionar no script de parse para o soot um arquivo com source e sink invertidos

### ISSUE THREAD

**Issue by rafaelmotaalves** [spgroup/miningframework#46]
Para testar se há tanto fluxos de left para right, como fluxos de right pra left é necessários executar o soot-analysis duas vezes, invertendo os parâmetros.

**Comment by rafaelmotaalves** [comment]
@pauloborba essa necessidade foi levantada na reunião de hoje (04/09) com Rodrigo.

**Comment by pauloborba** [comment]
OK, faz sentido.
