### ISSUE TITLE
Investigar caso em que o projeto já está configurado no travis

### ISSUE THREAD

**Issue by rafaelmotaalves** [spgroup/miningframework#57]

**Comment by pauloborba** [comment]
@rafaelmotaalves verificar casos similares em que excecoes possam estar quebrando o processo. melhor trata-las, registrar a mensagem de erro em log, e seguir adiante para o próximo cenário ou projeto.

**Comment by rafaelmotaalves** [comment]
@pauloborba não consegui reproduzir o erro, mas vou imprimir o erro retornado pelo travis para ficar mais transparente

**Comment by pauloborba** [comment]
@rafaelmotaalves foi @leusonmario que detectou? pede para ele verificar se ainda ocorre

**Comment by rafaelmotaalves** [comment]
@pauloborba ele disse que não está acontecendo mais
