### ISSUE TITLE
Reorganize directory structure

### ISSUE THREAD

**Issue by pauloborba** [spgroup/miningframework#67]
create services/projectProcessors (projectProcessors implementations go here)
          services/commitFilters (commitFilters implementations go here)
	  services/dataCollectors (dataCollectors implementations go here)
          services/outputProcessors (outputProcessors implementations go here)
	  services/configuration (module files go here)

   in case auxiliary files are needed for an interface implementation, we should
   create a subfolder for the implementation (like services/dataCollectors/ImplX)
   and include there both the auxiliary files and the implementation

**Comment by pauloborba** [comment]
fix links in README after changing this, and explain such rules

**Comment by rafaelmotaalves** [comment]
@pauloborba this structure was changed right? the right way would be dividing by instantiation? using a different folder for each research

**Comment by pauloborba** [comment]
@rafaelmotaalves a different folder for each empirical study/research would likely make reuse harder. when trying to implement a new filter for a new study, the researcher would have to look at the filters in many folders, navigating from folder to folder. moreover, what would we do when the same filter is used by two or more studies? 

on the other hand, developing/maintaining a study would be easier because all (or at least most, in case one of the services is the same as in a previous study) services are in a single folder, avoiding navigation across folders.  

overall, I would prioritize reuse. would you prefer to prioritize development?

**Comment by rafaelmotaalves** [comment]
ok, i think prioritizing reuse is the best aproach too.
