### ISSUE TITLE
Alocação de jar para cada cenário

### ISSUE THREAD

**Issue by pauloborba** [spgroup/miningframework#9]
idealmente, pegando build via travis. se não for possível, criando localmente.

**Comment by pauloborba** [comment]
marcar reunião com Léuson

**Comment by pauloborba** [comment]
@rafaelmotaalves primeiro tentar gerar apenas .class das classes do projeto. e aí faremos um estudo inicial apenas com isso. numa segunda fase, depois de avançar o estudo incial, tentaremos gerar .class/jar do projeto como um todo, incluindo as dependências.

**Comment by pauloborba** [comment]
@rafaelmotaalves prioridade atual

**Comment by rafaelmotaalves** [comment]
@pauloborba Pelo o que eu pesquisei, o travis não armazena os arquivos da build automáticamente, mas ele da a opção de dar deployment dessa build em algum serviço como ele explica nesse [link](https://docs.travis-ci.com/user/deployment). Acho que a melhor alternativa seria usar o Github Releases, dessa forma o passo a passo seria:
1. Criar um fork do projeto desejado
2. Modificar o .travis.yml para incluir a configuração de como salvar a build.
3. Forçar a build para cada um dos commits de merge.
4. Baixar as builds geradas.

**Comment by rafaelmotaalves** [comment]
Essa é a melhor alternativa mesmo? Algum desses outros serviços listados no link poderia ser utilizado?

**Comment by pauloborba** [comment]
> Essa é a melhor alternativa mesmo? Algum desses outros serviços listados no link poderia ser utilizado?

@rafaelmotaalves como isso compara com a solução adotada por guilherme e léuson?

**Comment by rafaelmotaalves** [comment]
A solução que guilherme mandou não salva os arquivos das builds, a solução de léuson, é parecida, a diferença sendo que não existe nenhuma biblioteca oficial do travis para java/groovy, tendo que usar a biblioteca http.

**Comment by pauloborba** [comment]
OK, melhor usar HTTP mesmo. e gerar a build apenas para os commits de merge que passaram pelo filtro.

**Comment by pauloborba** [comment]
@rafaelmotaalves falta algo aqui?

**Comment by rafaelmotaalves** [comment]
Não, acho que pra o que foi proposto já ta tudo implementado.
